  # GHC 8.6.5
resolver: lts-14.27
compiler: ghc-8.6.5

  # GHC 8.10.2
#resolver: nightly-2020-08-26
#compiler: ghc-8.10.2

packages:
  - contra-tracer
  - tracer-transformers
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-editor
  - plugins/backend-ekg
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/backend-trace-acceptor
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - examples

allow-newer: false

extra-deps:
  # needed for GHC 8.10.2
  #- async-timer-0.2.0.0
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1

  - time-units-1.0.0
  - katip-0.8.4.0

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 64351aaa3b27fd5a28fc7d1f9c48f9e5a815dab2
    subdirs:
        - Win32-network

  - git: https://github.com/CodiePP/libsystemd-journal
    commit: 4371464d5ae3fe1df4e3e77ab33156ad2d3bf1bd
    subdirs:
        - .

nix:
  # GHC 8.6.5
  shell-file: nix/stack-shell.nix
  # GHC 8.10.2
#  pure: false
#  packages: [ zlib.dev, zlib.out
#            , openssl.dev, openssl.out
#            , libsodium.dev, libsodium.out
#            #, haskell.compiler.ghc865
#            , haskell.compiler.ghc8102
#            , pkg-config
#            , systemd.dev
#            ]

