resolver: lts-13.15
compiler: ghc-8.6.4
packages:
- contra-tracer
- iohk-monitoring
extra-deps:
- time-units-1.0.0
- ekg-0.4.0.15
- ekg-json-0.1.0.6
- prometheus-2.1.1
- ekg-prometheus-adapter-0.1.0.4
- process-1.6.5.0
- transformers-0.5.6.2
- containers-0.5.11.0
- git: https://github.com/365andreas/katip-libsystemd-journal
  commit: 5f8d074c617fd67e3bce377a06d22b908b8ab8d7
- git: https://github.com/ocharles/libsystemd-journal
  commit: 16696812d6bf882fd348a54be9b573e9e115d2e3

nix:
  shell-file: scripts/nix/stack-shell.nix
