resolver: lts-14.27
compiler: ghc-8.6.5

packages:
  - contra-tracer
  - tracer-transformers
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-editor
  - plugins/backend-ekg
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/backend-trace-acceptor
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - examples

allow-newer: true

extra-deps:
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1

  - time-units-1.0.0
  - katip-0.8.4.0

  - libsystemd-journal-1.4.4

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 3b92f6e936e004753b46f3efabfbbb8539163ea1
    subdirs:
        - Win32-network

nix:
    shell-file: nix/stack-shell.nix
