resolver: lts-13.24
compiler: ghc-8.6.5
packages:
- contra-tracer
- iohk-monitoring
extra-deps:
- time-units-1.0.0
- ekg-0.4.0.15
- ekg-json-0.1.0.6
- prometheus-2.1.1
- ekg-prometheus-adapter-0.1.0.4
- process-1.6.5.0
- transformers-0.5.6.2
- containers-0.5.11.0
- libsystemd-journal-1.4.4

nix:
  shell-file: nix/stack-shell.nix
