resolver: lts-13.26
compiler: ghc-8.6.5
packages:
  - contra-tracer
  - tracer-transformers
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-editor
  - plugins/backend-ekg
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/backend-trace-acceptor
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - examples

extra-deps:
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - katip-0.8.3.0

nix:
  shell-file: nix/stack-shell.nix
