resolver: lts-13.26
compiler: ghc-8.6.5

packages:
  - contra-tracer
  - tracer-transformers
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-editor
  - plugins/backend-ekg
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/backend-trace-acceptor
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - examples

allow-newer: true

extra-deps:
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 7e89518148ebb11d9ee6b973c394a69713961de6
    subdirs:
        - Win32-network

nix:
    shell-file: nix/stack-shell.nix
