steps:
  - label: "code coverage (stack)"
    env:
      AWS_REGION: us-west-1
      S3_BUCKET: appveyor-ci-cache
      CACHE_S3_MAX_SIZE: 2500MB
      STACK_ROOT: "/build/iohk-monitoring.stack"
    command:
      # cache-s3 needs a build directory that is the same across all buildkite agents.
      # so copy the source into /build/iohk-monitoring
      - "rm -rf /build/iohk-monitoring"
      - "cp -R . /build/iohk-monitoring"
      - "cd /build/iohk-monitoring"
      - "nix-build --show-trace scripts/buildkite -o stack-rebuild"
      - "./stack-rebuild --show-trace"
    agents:
      system: x86_64-linux
    branches: "master"
    timeout: 30

  - label: "make TeX documentation"
    command: "cd docs; nix-shell --run make"
    agents:
      "system=x86_64-linux"
    artifact_paths: "docs/IOHK-Monitoring.pdf ; docs/IOHK-Monitoring.log"
    timeout: 5

  - label: 'check-hydra'
    command: 'ci/check-hydra.sh'
    agents:
      system: x86_64-linux
    timeout: 30

  - label: 'stack2nix'
    command: 'ci/check-stack2nix.sh'
    agents:
      system: x86_64-linux
    timeout: 30
